<?php
$datos = [
    ['Laura Gómez', 'Española', 'Amante de la lectura', 'Bibliotecaria', false],
    ['Miguel Ruiz', 'Mexicano', 'Especialista en TI', 'Desarrollador', true],
    ['Ana Martínez', 'Argentina', 'Viaja por el mundo', 'Fotógrafa', false],
    ['João Silva', 'Brasileño', 'Consultor de ventas', 'Comercial', true],
    ['Sofía Hernández', 'Colombiana', 'Mamá a tiempo completo', 'Ama de casa', false],
    ['David Torres', 'Peruano', 'Le encanta cocinar', 'Chef', true],
    ['María Rossi', 'Italiana', 'Amante del diseño', 'Arquitecta', true],
    ['Ahmed Ali', 'Marroquí', 'Ingeniero industrial', 'Ingeniero', true],
    ['Emma Johansson', 'Sueca', 'Ama la naturaleza', 'Bióloga', false],
    ['Lucas Fernández', 'Uruguayo', 'Coordinador de eventos', 'Relaciones públicas', true],
    ['Isabel Cruz', 'Colombiana', 'Artista plástica', 'Pintora', false],
    ['Carlos Mendoza', 'Chileno', 'Amante del fútbol', 'Entrenador', true],
    ['Laura Pérez', 'Venezolana', 'Estudiante de derecho', 'Estudiante', false],
    ['Juan Gómez', 'Español', 'Fotógrafo profesional', 'Fotógrafo', true],
    ['Marina López', 'Mexicana', 'Chef apasionada', 'Chef', false],
    ['Diego Fernández', 'Argentino', 'Consultor de negocios', 'Consultor', true],
    ['Ana Torres', 'Peruana', 'Ingeniera civil', 'Ingeniera', false],
    ['Jorge Sánchez', 'Colombiano', 'Músico', 'Músico', true],
    ['Sofía Castro', 'Cubana', 'Escritora', 'Escritora', false],
    ['Pablo Jiménez', 'Uruguayo', 'Profesor de matemáticas', 'Profesor', true],
    ['Elena Morales', 'Dominicana', 'Diseñadora gráfica', 'Diseñadora', false],
    ['Francisco Ruiz', 'Ecuatoriano', 'Empresario', 'Empresario', true],
    ['Luisa Díaz', 'Boliviana', 'Psicóloga', 'Psicóloga', false],
    ['Manuel Herrera', 'Panameño', 'Mecánico', 'Mecánico', true],
    ['Clara Rojas', 'Costarricense', 'Periodista', 'Periodista', false],
    ['Ricardo Flores', 'Guatemalteco', 'Programador', 'Programador', true],
    ['Natalia Ortiz', 'Paraguaya', 'Arquitecta', 'Arquitecta', false],
    ['Andrés Vázquez', 'Salvadoreño', 'Chef', 'Chef', true],
    ['Verónica Peña', 'Hondureña', 'Médica', 'Médica', false],
    ['Miguel Ángel', 'Nicaragüense', 'Abogado', 'Abogado', true],
    ['Patricia Morales', 'Costarricense', 'Fotógrafa', 'Fotógrafa', false],
    ['Javier Castillo', 'Mexicano', 'Ingeniero de software', 'Ingeniero', true],
    ['Adriana Ruiz', 'Colombiana', 'Docente universitaria', 'Profesora', false],
    ['Raúl Mendoza', 'Peruano', 'Consultor financiero', 'Consultor', true],
    ['María José', 'Boliviana', 'Estilista', 'Estilista', false],
    ['Felipe Gómez', 'Ecuatoriano', 'Músico', 'Músico', true],
    ['Lucía Torres', 'Venezolana', 'Enfermera', 'Enfermera', false],
    ['Sergio Hernández', 'Dominicano', 'Abogado', 'Abogado', true],
    ['Elisa Jiménez', 'Salvadoreña', 'Diseñadora', 'Diseñadora', false],
    ['Carlos Rivera', 'Guatemalteco', 'Fotógrafo', 'Fotógrafo', true],
    ['Ana María', 'Paraguaya', 'Psicóloga', 'Psicóloga', false],
    ['Jorge Ramírez', 'Nicaragüense', 'Chef', 'Chef', true],
    ['Sandra Díaz', 'Hondureña', 'Periodista', 'Periodista', false],
    ['Luis Castro', 'Panameño', 'Mecánico', 'Mecánico', true],
    ['Marta López', 'Costarricense', 'Estudiante', 'Estudiante', false],
    ['Ricardo Sánchez', 'Salvadoreño', 'Programador', 'Programador', true],
    ['Gabriela Rojas', 'Guatemalteca', 'Abogada', 'Abogada', false],
    ['David Vargas', 'Paraguayo', 'Diseñador gráfico', 'Diseñador', true],
    ['Laura Jiménez', 'Mexicana', 'Chef', 'Chef', false],
    ['Javier Ortiz', 'Colombiano', 'Ingeniero', 'Ingeniero', true],
    ['Sofía Fernández', 'Peruana', 'Médica', 'Médica', false],
    ['Mario González', 'Boliviano', 'Abogado', 'Abogado', true],
    ['Carla Mendoza', 'Ecuatoriana', 'Psicóloga', 'Psicóloga', false],
    ['José Morales', 'Venezolano', 'Profesor', 'Profesor', true],
    ['Mónica Pérez', 'Dominicana', 'Fotógrafa', 'Fotógrafa', false],
    ['Fernando Sánchez', 'Salvadoreño', 'Consultor', 'Consultor', true],
];

$contactos = [
    ['laura.gomez@email.com', '612345678'],
    ['miguel.ruiz@email.com', '5523456789'],
    ['ana.martinez@email.com', '1134567890'],
    ['joao.silva@email.com', '2198765432'],
    ['sofia.hernandez@email.com', '3104567890'],
    ['david.torres@email.com', '987654321'],
    ['maria.rossi@email.com', '3456789012'],
    ['ahmed.ali@email.com', '0612345678'],
    ['emma.johansson@email.com', '0701234567'],
    ['lucas.fernandez@email.com', '099123456'],
    ['isabel.cruz@email.com', '612345679'],
    ['carlos.mendoza@email.com', '5523456790'],
    ['laura.perez@email.com', '1134567891'],
    ['juan.gomez@email.com', '2198765433'],
    ['marina.lopez@email.com', '3104567891'],
    ['diego.fernandez@email.com', '987654322'],
    ['ana.torres@email.com', '3456789013'],
    ['jorge.sanchez@email.com', '0612345679'],
    ['sofia.castro@email.com', '0701234568'],
    ['pablo.jimenez@email.com', '099123457'],
    ['elena.morales@email.com', '612345680'],
    ['francisco.ruiz@email.com', '5523456791'],
    ['luisa.diaz@email.com', '1134567892'],
    ['manuel.herrera@email.com', '2198765434'],
    ['clara.rojas@email.com', '3104567892'],
    ['ricardo.flores@email.com', '987654323'],
    ['natalia.ortiz@email.com', '3456789014'],
    ['andres.vazquez@email.com', '0612345680'],
    ['veronica.pena@email.com', '0701234569'],
    ['miguel.angel@email.com', '099123458'],
    ['patricia.morales@email.com', '612345681'],
    ['javier.castillo@email.com', '5523456792'],
    ['adriana.ruiz@email.com', '1134567893'],
    ['raul.mendoza@email.com', '2198765435'],
    ['maria.jose@email.com', '3104567893'],
    ['felipe.gomez@email.com', '987654324'],
    ['lucia.torres@email.com', '3456789015'],
    ['sergio.hernandez@email.com', '0612345681'],
    ['elisa.jimenez@email.com', '0701234570'],
    ['carlos.rivera@email.com', '099123459'],
    ['ana.maria@email.com', '612345682'],
    ['jorge.ramirez@email.com', '5523456793'],
    ['sandra.diaz@email.com', '1134567894'],
    ['luis.castro@email.com', '2198765436'],
    ['marta.lopez@email.com', '3104567894'],
    ['ricardo.sanchez@email.com', '987654325'],
    ['gabriela.rojas@email.com', '3456789016'],
    ['david.vargas@email.com', '0612345682'],
    ['laura.jimenez@email.com', '0701234571'],
    ['javier.ortiz@email.com', '099123460'],
    ['sofia.fernandez@email.com', '612345683'],
    ['mario.gonzalez@email.com', '5523456794'],
    ['carla.mendoza@email.com', '1134567895'],
    ['jose.morales@email.com', '2198765437'],
    ['monica.perez@email.com', '3104567895'],
    ['fernando.sanchez@email.com', '987654326'],
];
